# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:    
    branches:    
      - master
env:
  api_key: ${{ secrets.api_key }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run python code
      run: python streaming.py
   
